import {useEffect,useMemo,useState} from 'react';
import {SKILLS,type SkillName} from './lib/osrs/skills';
import {xpForLevel} from './lib/osrs/xp';
import {loadProfile,saveProfile,exportProfile,importProfile,type Profile} from './lib/storage/profile';
import type {Snapshot} from './lib/osrs/hiscores';
import {fetchPlayer} from './lib/osrs/wom';
import './styles.css';
const nf=new Intl.NumberFormat();
const defaultRates:Partial<Record<SkillName,number>>={Herblore:220000,Fishing:55000,Cooking:300000,Slayer:45000,Mining:70000,Woodcutting:65000,Construction:450000,Runecraft:60000,Sailing:60000};
function demoSnapshot():Snapshot{const levels:Partial<Record<SkillName,number>>={Ranged:99,Strength:98,Slayer:89,Prayer:82,Herblore:73,Woodcutting:76,Fishing:79,Cooking:82,Construction:76,Sailing:71};const skills={} as Snapshot['skills'];let tl=0,tx=0;for(const s of SKILLS){const level=levels[s]??75;const xp=xpForLevel(level);skills[s]={level,xp,rank:1};tl+=level;tx+=xp}return{username:'Kevbrosia',table:'main',totalLevel:tl,totalXp:tx,fetchedAt:new Date().toISOString(),skills}}
const tabs=['Skills','Train','Log','Goals','Training Planner'] as const; type Tab=typeof tabs[number];
export default function App(){const [username,setUsername]=useState('Kevbrosia');const [snap,setSnap]=useState<Snapshot>(()=>demoSnapshot());const [profile,setProfile]=useState<Profile>(()=>loadProfile('Kevbrosia'));const [tab,setTab]=useState<Tab>('Skills');const [status,setStatus]=useState('Local baseline loaded. Live Jagex lookup is the next integration step.');const [goalText,setGoalText]=useState('');const [logName,setLogName]=useState('');const [logSource,setLogSource]=useState('');const [planSkill,setPlanSkill]=useState<SkillName>('Herblore');const [loading,setLoading]=useState(false);const [ioStatus,setIoStatus]=useState('');
useEffect(()=>saveProfile(profile),[profile]);
const rows=useMemo(()=>SKILLS.map(name=>{const cur=snap.skills[name];const target=profile.targets[name];const remain=target?Math.max(0,xpForLevel(target)-cur.xp):0;return{name,...cur,target,remain}}),[snap,profile]);
function setTarget(name:SkillName,value:string){const n=value?Number(value):undefined;if(n!==undefined&&(n<snap.skills[name].level||n>99))return;setProfile(p=>({...p,targets:{...p.targets,[name]:n}}))}
function setRate(name:SkillName,value:string){const n=Math.max(0,Number(value)||0);setProfile(p=>({...p,rates:{...p.rates,[name]:n}}))}
async function lookup(){const u=username.trim();if(!u||loading)return;setLoading(true);setStatus(`Looking up ${u}…`);try{const live=await fetchPlayer(u);setSnap(live);if(u.toLowerCase()!==profile.username.toLowerCase())setProfile(loadProfile(u));setStatus(`Live snapshot loaded · ${new Date(live.fetchedAt).toLocaleString()}`)}catch(e){setStatus(e instanceof Error?e.message:'Player lookup failed.')}finally{setLoading(false)}}
function addGoal(){const title=goalText.trim();if(!title)return;setProfile(p=>({...p,goals:[...p.goals,{id:crypto.randomUUID(),title,done:false}]}));setGoalText('')}
function backup(){const blob=new Blob([exportProfile(profile)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`osrs-ledger-${profile.username.toLowerCase().replace(/\s+/g,'-')}.json`;a.click();URL.revokeObjectURL(url);setIoStatus('Profile backup exported.')}
async function restore(file:File|undefined){if(!file)return;try{const raw=await file.text();setProfile(importProfile(raw,snap.username));setIoStatus('Profile backup restored.')}catch(e){setIoStatus(e instanceof Error?e.message:'Could not restore profile.')}}
function addLog(){const name=logName.trim();if(!name)return;setProfile(p=>({...p,log:[...p.log,{id:crypto.randomUUID(),name,source:logSource.trim()||'Custom',obtained:false}]}));setLogName('');setLogSource('')}
const plan=rows.find(r=>r.name===planSkill)!;const rate=profile.rates[planSkill]??defaultRates[planSkill]??50000;const target=plan.target??Math.min(99,plan.level+1);const remain=Math.max(0,xpForLevel(target)-plan.xp);const hours=rate?remain/rate:0;
return <main><header><div><div className="eyebrow">PLAYER PROGRESS SYSTEM</div><h1>OSRS <span>Ledger</span></h1><p>Live stats stay separate from your goals, plans and collection progress.</p></div><div className="lookup"><input value={username} onChange={e=>setUsername(e.target.value)} maxLength={12}/><button onClick={lookup} disabled={loading}>{loading?'Loading…':'Lookup'}</button></div></header>
<section className="hero"><div><small>PLAYER</small><h2>{snap.username}</h2><b>{nf.format(snap.totalLevel)} total · {snap.table}</b></div><div><small>TOTAL XP</small><h2>{nf.format(snap.totalXp)}</h2><b>24 skills tracked</b></div><div><small>ACTIVE GOALS</small><h2>{profile.goals.filter(g=>!g.done).length}</h2><b>{profile.log.filter(x=>x.obtained).length} log items obtained</b></div></section>
<div className="tools"><button onClick={backup}>Export profile</button><label className="importBtn">Import profile<input type="file" accept="application/json,.json" onChange={e=>restore(e.target.files?.[0])}/></label><span>{ioStatus}</span></div><nav>{tabs.map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav><p className="status">{status}</p>
{tab==='Skills'&&<section className="card"><div className="thead"><span>Skill</span><span>Level</span><span>XP</span><span>Target</span><span>XP remaining</span></div>{rows.map(r=><div className="row" key={r.name}><strong>{r.name}</strong><span>{r.level}</span><span>{nf.format(r.xp)}</span><input aria-label={`${r.name} target`} type="number" min={r.level} max="99" placeholder="—" value={r.target??''} onChange={e=>setTarget(r.name,e.target.value)}/><span className={r.target&&r.remain===0?'done':''}>{r.target?(r.remain===0?'Completed':nf.format(r.remain)):'—'}</span></div>)}</section>}
{tab==='Train'&&<section className="grid">{rows.filter(r=>r.target&&r.remain>0).length?rows.filter(r=>r.target&&r.remain>0).map(r=>{const rr=profile.rates[r.name]??defaultRates[r.name]??50000;return <article className="tile" key={r.name}><small>{r.name.toUpperCase()}</small><h2>{r.level} → {r.target}</h2><p>{nf.format(r.remain)} XP remaining</p><label>XP / hour<input type="number" value={rr} onChange={e=>setRate(r.name,e.target.value)}/></label><b>≈ {(r.remain/rr).toFixed(1)} hours</b></article>}):<Empty title="No training targets yet" text="Set a target on the Skills tab and it will appear here automatically."/>}</section>}
{tab==='Goals'&&<section className="card"><div className="composer"><input placeholder="e.g. Reach 2,000 total" value={goalText} onChange={e=>setGoalText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addGoal()}/><button onClick={addGoal}>Add goal</button></div>{profile.goals.length?profile.goals.map(g=><div className="goal" key={g.id}><input type="checkbox" checked={g.done} onChange={()=>setProfile(p=>({...p,goals:p.goals.map(x=>x.id===g.id?{...x,done:!x.done}:x)}))}/><span className={g.done?'strike':''}>{g.title}</span><button className="ghost" onClick={()=>setProfile(p=>({...p,goals:p.goals.filter(x=>x.id!==g.id)}))}>Remove</button></div>):<Empty title="No goals saved" text="Add account milestones, diary goals, quest goals, gear goals, or anything else you want to track."/>}</section>}
{tab==='Log'&&<section className="card"><div className="composer logform"><input placeholder="Item / drop" value={logName} onChange={e=>setLogName(e.target.value)}/><input placeholder="Source (e.g. Kraken)" value={logSource} onChange={e=>setLogSource(e.target.value)}/><button onClick={addLog}>Add</button></div>{profile.log.length?profile.log.map(i=><div className="goal" key={i.id}><input type="checkbox" checked={i.obtained} onChange={()=>setProfile(p=>({...p,log:p.log.map(x=>x.id===i.id?{...x,obtained:!x.obtained}:x)}))}/><span className={i.obtained?'strike':''}><strong>{i.name}</strong> <em>· {i.source}</em></span><button className="ghost" onClick={()=>setProfile(p=>({...p,log:p.log.filter(x=>x.id!==i.id)}))}>Remove</button></div>):<Empty title="Collection Log foundation" text="Add drops you care about now. Automatic OSRS collection-log catalogs can plug into this model later."/>}</section>}
{tab==='Training Planner'&&<section className="planner"><div className="card"><label>Skill<select value={planSkill} onChange={e=>setPlanSkill(e.target.value as SkillName)}>{SKILLS.map(s=><option key={s}>{s}</option>)}</select></label><label>Target level<input type="number" min={plan.level} max="99" value={target} onChange={e=>setTarget(planSkill,e.target.value)}/></label><label>Expected XP / hour<input type="number" value={rate} onChange={e=>setRate(planSkill,e.target.value)}/></label></div><div className="planresult"><small>TRAINING ESTIMATE</small><h2>{planSkill} {plan.level} → {target}</h2><div className="big">{nf.format(remain)} XP</div><p>At {nf.format(rate)} XP/hour, approximately <strong>{hours.toFixed(1)} hours</strong> remain.</p><div className="bar"><span style={{width:`${Math.min(100,Math.max(3,(plan.xp/xpForLevel(target))*100))}%`}}/></div><p className="muted">Rate is editable because gear, attention level and training method change real XP/hour.</p></div></section>}
</main>}
function Empty({title,text}:{title:string,text:string}){return <div className="empty"><h2>{title}</h2><p>{text}</p></div>}
